// Arrow routing from the draw.io file (anchors.json, generated by scripts/sync-anchors.js): the anchors, waypoints and style of
// each edge, matched by its page, ends and label, written into the edge's slots 3-6.
import { EDGE_SLOT } from "./page.js";

export function applyAnchors(flow, records) {
  for (const record of records) {
    const edge = flow[record.p].edges.find(
      (candidate) =>
        candidate[EDGE_SLOT.FROM] === record.f &&
        candidate[EDGE_SLOT.TO] === record.t &&
        (candidate[EDGE_SLOT.LABEL] || null) === (record.l || null),
    );
    if (!edge) continue;
    edge[EDGE_SLOT.WAYPOINTS] = record.wp || edge[EDGE_SLOT.WAYPOINTS] || null;
    if (record.an)
      edge[EDGE_SLOT.ANCHORS] = { ...edge[EDGE_SLOT.ANCHORS], ...record.an };
    if (record.elbow) edge[EDGE_SLOT.STYLE] = "elbow";
    if (record.nolabel) edge[EDGE_SLOT.HIDE_LABEL] = true;
  }
}
