import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default [
  {
    ignores: [
      "node_modules/",
      "index.html", // build output of build.py
      "src/anchors.js", // generated by sync_anchors.py
    ],
  },
  js.configs.recommended,
  {
    // Browser sources: concatenated into one <script> by build.py. Each file is an IIFE that
    // shares data through window.QB* globals, so they are classic scripts, not modules.
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: { ...globals.browser },
    },
  },
  {
    // Node test scripts (CommonJS, require()). `window` is the fake window that test/load.js installs on
    // `global`, and the real one inside Playwright page.evaluate() callbacks in smoke.js and shot.js.
    files: ["test/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: { ...globals.node, window: "readonly" },
    },
  },
  {
    files: ["*.mjs"],
    languageOptions: { ecmaVersion: 2022, sourceType: "module", globals: { ...globals.node } },
  },
  {
    rules: {
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-unused-vars": ["error", { args: "none", caughtErrors: "none", destructuredArrayIgnorePattern: "^_" }],
    },
  },
  prettier, // keep last: turns off rules that conflict with Prettier formatting
];
