import { page } from "../page.js";

export default page(
  "Army",
  "AR",
  {
    start: ["S", 10, 10, 120, 60, "Army"],
    threatEx: ["D", 10, 100, 120, 60, "*Threat* exists"],
    mobAdjThreat: ["d", 10, 280, 120, 60, "*Mobile* army adjacent to *threat*"],
    attackT: ["A", 10, 370, 120, 60, "Attack"],
    formMob: [
      "d",
      170,
      280,
      120,
      60,
      "Possible to form a *mobile* army adjacent to *threat*",
    ],
    moveT: ["A", 170, 370, 120, 60, "Move"],
    incVal: [
      "d",
      330,
      280,
      120,
      60,
      "Possible to move an army to increase *value* at *threatened* stronghold",
    ],
    towardsThreat: [
      "d",
      330,
      370,
      120,
      60,
      "*Mobile* army’s closest *target* takes it towards cause of *threat*",
    ],
    exposedEx: ["D", 330, 100, 120, 60, "*Exposed* *target* exists"],
    moveExposed: [
      "A",
      330,
      190,
      120,
      60,
      "Move nearest army towards *exposed*",
    ],
    start2: ["S", 498, 10, 120, 60, "Army 2"],
    mobAdjTgt: ["D", 498, 100, 120, 60, "*Mobile* army adjacent to *target*"],
    notSiege: ["d", 498, 190, 120, 50, "*Target* not under siege"],
    atkPri: [
      "P",
      480,
      270,
      155,
      160,
      "Priority:",
      {
        items: [
          "*Target* is nation at war",
          "Attack would not move nation to war",
          "*Target* in active nation",
          "Highest *value* Shadow army",
        ],
      },
    ],
    attackA: ["A", 660, 370, 120, 60, "Attack"],
    start3: ["S", 660, 10, 120, 60, "Army 3"],
    intoFs: [
      "D",
      660,
      100,
      120,
      60,
      "Army can move into Fellowship region without increasing distance to *target*",
    ],
    huntDice: [
      "d",
      655,
      190,
      130,
      60,
      "Dice in hunt pool and Fellowship Progress puts it outside Mordor and no army in region",
    ],
    moveFs: ["A", 660, 280, 120, 60, "Move army into region"],
    startEv: ["S", 825, 10, 120, 60, "Army Event card"],
    emptySet: [
      "D",
      825,
      100,
      120,
      60,
      "Army can move into an empty settlement of a nation at war",
    ],
    incDist: ["d", 825, 190, 120, 60, "Increases distance to *target*"],
    move1: ["A", 825, 280, 120, 60, "Move 1 unit into region"],
    moveSet: ["A", 990, 190, 120, 60, "Move army into region"],
    merge: [
      "D",
      60,
      490,
      120,
      60,
      "Two Shadow armies able to merge at least one is not *mobile*",
    ],
    mergeGood: [
      "d",
      40,
      580,
      160,
      60,
      "Would increase number of *mobile* armies or make one of higher *value* than either currently is",
    ],
    mergePri: [
      "P",
      10,
      670,
      220,
      140,
      "Priority:",
      {
        items: [
          "Decrease distance to *target*",
          "Creates the highest *value* army possible",
          "Moves furthest army from closest *target*",
          "Least left-over units",
          "Destination contains stronghold",
        ],
      },
    ],
    moveM: ["A", 260, 710, 120, 60, "Move"],
    start4: ["S", 825, 370, 120, 60, "Army 4"],
    mobTowards: [
      "D",
      468,
      490,
      120,
      60,
      "*Mobile* army can move or attack towards closest *target*",
    ],
    movePri: [
      "P",
      400,
      580,
      260,
      160,
      "Priority:",
      {
        items: [
          "Shadow army adjacent to *target*",
          "*Target* nation at war",
          "Doesn’t make passive nation active",
          "Doesn't change nation to at war",
          "By order of *target* priority",
          "Highest *value* Shadow army",
          "Doesn’t block another *mobile* army’s shortest route to their closest *target*",
          "Region contains Fellowship",
        ],
      },
    ],
    moveAttack: ["A", 470, 760, 120, 60, "Move/Attack"],
    anyArmy: ["D", 740, 490, 120, 60, "Have an army on the board"],
    nonMobPri: [
      "P",
      680,
      580,
      240,
      160,
      "Priority:",
      {
        items: [
          "Doesn't change nation to at war",
          "Create highest army *value* possible",
          "Closest *target* has *passive* army adjacent",
          "Movement ends adjacent to another Shadow army",
          "Decreases distance to closest *target*",
          "Highest *value* Shadow army",
        ],
      },
    ],
    moveN: ["A", 740, 760, 120, 60, "Move"],
    ret: ["J", 930, 490, 120, 60, "Phase 5 - continue from where you came"],
    title: ["N", 1070, 10, 90, 60, "Army"],
    note: [
      "N",
      950,
      57,
      210,
      30,
      "Navigate twice for army die moves if both are not used for one condition",
    ],
  },
  [
    ["start", "threatEx"],
    ["threatEx", "mobAdjThreat", "Yes"],
    ["threatEx", "exposedEx", "No"],
    ["mobAdjThreat", "attackT", "Yes"],
    ["mobAdjThreat", "formMob", "No"],
    ["formMob", "moveT", "Yes"],
    ["formMob", "incVal", "No"],
    [
      "incVal",
      "moveT",
      "Yes",
      [
        [390, 350],
        [310, 350],
        [310, 400],
      ],
    ],
    ["incVal", "towardsThreat", "No"],
    ["towardsThreat", "moveT", "Yes"],
    ["towardsThreat", "exposedEx", "No"],
    ["exposedEx", "moveExposed", "Yes"],
    ["exposedEx", "mobAdjTgt", "No"],
    ["start2", "mobAdjTgt"],
    ["mobAdjTgt", "notSiege", "Yes"],
    ["mobAdjTgt", "intoFs", "No"],
    ["notSiege", "atkPri", "Yes"],
    [
      "notSiege",
      "intoFs",
      "No",
      [
        [640, 220],
        [640, 130],
      ],
    ],
    ["atkPri", "attackA"],
    ["start3", "intoFs"],
    ["intoFs", "huntDice", "Yes"],
    ["intoFs", "emptySet", "No"],
    ["huntDice", "moveFs", "Yes"],
    ["huntDice", "emptySet", "No"],
    ["startEv", "emptySet"],
    ["emptySet", "incDist", "Yes"],
    [
      "emptySet",
      "merge",
      "No",
      [
        [1140, 130],
        [1140, 470],
        [120, 470],
      ],
    ],
    ["incDist", "move1", "Yes"],
    ["incDist", "moveSet", "No"],
    ["merge", "mergeGood", "Yes"],
    ["merge", "mobTowards", "No"],
    ["mergeGood", "mergePri", "Yes"],
    ["mergeGood", "mobTowards", "No"],
    ["mergePri", "moveM"],
    [
      "start4",
      "mobTowards",
      null,
      [
        [885, 450],
        [528, 450],
      ],
    ],
    ["mobTowards", "movePri", "Yes"],
    ["mobTowards", "anyArmy", "No"],
    ["movePri", "moveAttack"],
    ["anyArmy", "nonMobPri", "Yes"],
    ["anyArmy", "ret", "No"],
    ["nonMobPri", "moveN"],
  ],
);
