import { page } from "../page.js";

export default page(
  "Battle",
  "BA",
  {
    start: ["S", 10, 10, 120, 60, "Battle"],
    rearGuard: [
      "T",
      10,
      100,
      120,
      60,
      "Troops from nations not at war form rear-guard",
    ],
    downgrade: [
      "T",
      10,
      190,
      120,
      60,
      "Downgrade elite to continue siege if necessary",
    ],
    startNext: ["S", 10, 280, 120, 60, "Battle\n(next round)"],
    defStrong: [
      "D",
      170,
      100,
      120,
      60,
      "Shadow army defending in stronghold region and not under siege",
    ],
    valLow: [
      "d",
      170,
      190,
      120,
      62,
      "Army *value* lower than or equal to enemy and less than 8 Army units",
    ],
    retreatIn: ["A", 170, 280, 120, 60, "Retreat into stronghold"],
    attacking: ["D", 360, 100, 120, 60, "Shadow army attacking"],
    sortie: ["d", 360, 359, 120, 60, "Army is a sortie"],
    playChar: ["d", 360, 451, 120, 60, "Holding a *playable* character card"],
    sortiePri: [
      "P",
      130,
      426,
      197,
      110,
      "Priority:",
      {
        items: [
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile or add corruption",
          "Ascending order of initiative",
        ],
      },
    ],
    wkFirst: [
      "d",
      534,
      359,
      120,
      60,
      "Army includes the Witch King and this is the first round of battle",
    ],
    wkPri: [
      "P",
      496,
      440,
      197,
      140,
      "Priority:",
      {
        items: [
          "Strategy card",
          "Durin's Bane",
          "Character card",
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile or add corruption",
          "Ascending order of initiative",
        ],
      },
    ],
    laySiege: ["d", 690, 359, 120, 60, "Shadow is laying siege"],
    more4: [
      "d",
      850,
      359,
      120,
      60,
      "Holding more than four Event cards - excluding Faction Event cards",
    ],
    ctb: ["d", 1010, 359, 120, 60, "Holding a *playable* Call to Battle card"],
    atkPri: [
      "P",
      709,
      440,
      250,
      140,
      "Priority:",
      {
        items: [
          "Durin's Bane",
          "Call to Battle card",
          "Strategy card",
          "Character card",
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile or add corruption",
          "Ascending order of initiative",
        ],
      },
    ],
    besieged: [
      "D",
      520,
      100,
      120,
      60,
      "Besieged or fighting in a stronghold region",
    ],
    round1: ["D", 690, 100, 120, 60, "Round 1 of combat"],
    defPri: [
      "P",
      440,
      190,
      280,
      130,
      "Priority:",
      {
        items: [
          "Strategy card which cancels the Free Peoples card",
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile or add corruption",
          "Ascending order of initiative on Character cards",
        ],
      },
    ],
    regionPri: [
      "P",
      850,
      70,
      304,
      200,
      "Region priority:",
      {
        items: [
          "Doesn’t create *threat*",
          "Reduces distance to closest *target* or *exposed*",
          "Region which increases the number of *mobile* armies",
          "Region which increases the number of *aggressive* armies",
          "Settlement",
          "Region containing highest *value* Shadow army possible",
          "Region adjacent to highest *value* Shadow army possible",
        ],
      },
    ],
    retreat: ["A", 942, 290, 120, 60, "Retreat"],
    playCard: ["T", 10, 631, 120, 60, "Play card"],
    rollDice: ["T", 170, 631, 120, 60, "Roll dice"],
    reroll: ["T", 330, 631, 120, 60, "Re-roll misses"],
    casualties: [
      "T",
      490,
      629,
      240,
      128,
      "Remove casualties:",
      {
        items: [
          "Maximise the effects of any cards played",
          "Maintain the highest army *value* with the lowest number of army units",
          "Keep at least one unit of each nation",
        ],
      },
    ],
    fpRemain: ["D", 770, 631, 120, 60, "Free People remain"],
    anyCond: [
      "D",
      1010,
      600,
      140,
      121,
      "ANY condition true:",
      {
        items: [
          "Wins the game",
          "Decreases distance to closest *target*",
          "Negates *threat*",
        ],
        any: true,
      },
    ],
    moveMax: ["A", 1020, 510, 120, 60, "Move maximum *value* into region"],
    endA: ["A", 1020, 752, 120, 60, "End"],
    fieldOrMil: [
      "d",
      770,
      752,
      120,
      60,
      "Field battle or using military strategy or Fellowship on Mordor track",
    ],
    aggrCont: [
      "d",
      330,
      747,
      140,
      71,
      "Shadow army is *aggressive* if battle continues or is defending or Fellowship on Mordor track",
    ],
    endB: ["A", 10, 751, 120, 60, "End"],
    nextRound: ["J", 168, 752, 120, 60, "Battle\n(next round)"],
    title: ["N", 1060, 10, 100, 60, "Battle"],
  },
  [
    ["start", "rearGuard"],
    ["rearGuard", "defStrong", null, null, { ex: [1, 0.5], en: [0, 0.5] }],
    ["startNext", "downgrade"],
    ["downgrade", "defStrong", null, null, { ex: [1, 0.5], en: [0, 0.5] }],
    ["defStrong", "valLow", "Yes"],
    ["defStrong", "attacking", "No"],
    ["valLow", "retreatIn", "Yes"],
    ["valLow", "attacking"],
    ["attacking", "sortie", "Yes"],
    ["attacking", "besieged", "No"],
    ["sortie", "playChar", "Yes"],
    ["sortie", "wkFirst", "No"],
    ["playChar", "sortiePri", "Yes"],
    [
      "playChar",
      "rollDice",
      "No",
      [
        [420, 550],
        [230, 550],
      ],
    ],
    ["sortiePri", "playCard"],
    ["wkFirst", "wkPri", "Yes"],
    ["wkFirst", "laySiege", "No"],
    [
      "wkPri",
      "playCard",
      null,
      [
        [480, 545],
        [480, 590],
        [70, 590],
      ],
    ],
    [
      "laySiege",
      "atkPri",
      null,
      [
        [750, 430],
        [834, 430],
      ],
    ],
    ["laySiege", "more4", "No"],
    [
      "more4",
      "atkPri",
      "Yes",
      [
        [910, 430],
        [834, 430],
      ],
    ],
    ["more4", "ctb", "No"],
    [
      "ctb",
      "atkPri",
      null,
      [
        [1070, 430],
        [834, 430],
      ],
    ],
    [
      "ctb",
      "rollDice",
      "No",
      [
        [1140, 389],
        [1140, 490],
        [980, 490],
        [980, 610],
        [230, 610],
      ],
    ],
    [
      "atkPri",
      "playCard",
      null,
      [
        [834, 590],
        [70, 590],
      ],
    ],
    ["besieged", "defPri", "Yes"],
    ["besieged", "round1", "No"],
    [
      "round1",
      "defPri",
      null,
      [
        [740, 170],
        [580, 170],
      ],
    ],
    ["round1", "regionPri", "No"],
    [
      "defPri",
      "playCard",
      null,
      [
        [580, 350],
        [70, 350],
      ],
    ],
    ["regionPri", "retreat"],
    ["playCard", "rollDice"],
    ["rollDice", "reroll"],
    ["reroll", "casualties"],
    ["casualties", "fpRemain"],
    ["fpRemain", "fieldOrMil", "Yes"],
    ["fpRemain", "anyCond", "No"],
    ["anyCond", "moveMax", "Yes"],
    ["anyCond", "endA", "No"],
    ["fieldOrMil", "aggrCont", "Yes"],
    ["fieldOrMil", "endA", "No"],
    [
      "aggrCont",
      "endB",
      "No",
      [
        [395, 710],
        [70, 710],
      ],
    ],
    ["aggrCont", "nextRound", "Yes"],
  ],
);
