import { page } from "../page.js";

export default page(
  "Character",
  "CH",
  {
    start: ["S", 10, 10, 120, 60, "Character"],
    aggr: [
      "D",
      10,
      93,
      120,
      85,
      "Army *aggressive* against adjacent *target* and contains Witch King or maximum possible leadership",
    ],
    attack: ["A", 10, 210, 120, 60, "Attack"],
    mobLead: [
      "D",
      170,
      97,
      120,
      76,
      "*Mobile* army with leadership and a valid move/attack towards nearest available *target*",
    ],
    jArmy4c: ["J", 170, 210, 120, 60, "Army 4\n(use character die)"],
    start2: ["S", 330, 10, 120, 60, "Character 2"],
    nazInPlay: ["D", 330, 105, 120, 60, "Nazgûl or Witch King in play"],
    jEventC: ["J", 490, 105, 120, 60, "Event (use character die)"],
    wkJoin: [
      "d",
      230,
      310,
      120,
      60,
      "Witch King not in a *mobile* army and is able to join or create one",
    ],
    wkPri: [
      "P",
      170,
      400,
      240,
      230,
      "Witch King placement priority:",
      {
        items: [
          "Adjacent to sieging *threat*",
          "Army is *mobile*",
          "*Target* nation is at war",
          "Army becomes *mobile* when Witch King added",
          "Opposing army does not contain Gandalf the White",
          "Opposing army does not contain hobbits",
          "Adjacent to *threat*",
          "Sieging",
          "Adjacent to *target*",
          "Highest *value* Shadow army",
        ],
      },
    ],
    moveMuster: ["T", 230, 655, 120, 60, "Move/Muster"],
    musteredWK: ["d", 230, 745, 120, 60, "Mustered Witch King"],
    endA: ["A", 10, 745, 120, 60, "End action"],
    start3: ["S", 10, 485, 120, 60, "Character 3 / Muster Witch King"],
    nazFs: [
      "d",
      450,
      310,
      120,
      60,
      "Nazgûl not in *Fellowship region* and are able to move there",
    ],
    nazJoin: [
      "d",
      620,
      310,
      120,
      60,
      "Nazgûl not in a *mobile* army and are able to join or create one",
    ],
    nazPri: [
      "P",
      450,
      400,
      290,
      260,
      "Nazgûl placement priority:\nGather all Nazgûl prior to placement",
      {
        items: [
          "One in region which contains the Fellowship",
          "Adjacent to sieging *threat*",
          "Leadership value less than number of army units and 5",
          "Contains Witch King",
          "Shadow stronghold under siege",
          "*Mobile* army",
          "Adjacent to *threat*",
          "*Target* nation is active",
          "Army becomes *mobile* with Nazgûl",
          "Not sieging",
          "Adjacent to *target*",
          "Highest *value* Shadow army",
        ],
      },
    ],
    move: ["T", 535, 690, 120, 60, "Move"],
    mosMob: [
      "d",
      820,
      310,
      120,
      60,
      "Mouth of Sauron is not in a *mobile* army",
    ],
    mosPri: [
      "P",
      780,
      400,
      200,
      153,
      "Mouth of Sauron movement priority:",
      {
        items: [
          "Leadership value less than number of army units and 5",
          "*Mobile* army",
          "Army adjacent to *target*",
          "Can be reached on this die",
          "Closest army",
        ],
      },
    ],
    moveToArmy: ["T", 820, 580, 120, 60, "Move towards army"],
    dieUsed: ["d", 1020, 310, 120, 60, "Die has been used"],
    endB: ["A", 1020, 400, 120, 60, "End action"],
    title: ["N", 1000, 10, 160, 60, "Character"],
  },
  [
    ["start", "aggr"],
    ["aggr", "attack", "Yes"],
    ["aggr", "mobLead", "No"],
    ["mobLead", "jArmy4c", "Yes"],
    ["mobLead", "nazInPlay", "No"],
    ["start2", "nazInPlay"],
    ["nazInPlay", "jEventC", "No"],
    [
      "nazInPlay",
      "wkJoin",
      "Yes",
      [
        [390, 290],
        [290, 290],
      ],
    ],
    ["wkJoin", "wkPri", "Yes"],
    ["wkJoin", "nazFs", "No"],
    ["wkPri", "moveMuster"],
    ["moveMuster", "musteredWK"],
    ["musteredWK", "endA", "Yes"],
    [
      "musteredWK",
      "nazPri",
      "No",
      [
        [430, 775],
        [430, 524],
      ],
    ],
    ["start3", "wkPri"],
    [
      "nazFs",
      "nazPri",
      "Yes",
      [
        [510, 380],
        [595, 380],
      ],
    ],
    ["nazFs", "nazJoin", "No"],
    [
      "nazJoin",
      "nazPri",
      "Yes",
      [
        [680, 380],
        [595, 380],
      ],
    ],
    ["nazJoin", "mosMob", "No"],
    ["nazPri", "move"],
    [
      "move",
      "mosMob",
      null,
      [
        [760, 720],
        [760, 340],
      ],
    ],
    ["mosMob", "mosPri", "Yes"],
    ["mosMob", "dieUsed", "No"],
    ["mosPri", "moveToArmy"],
    [
      "moveToArmy",
      "dieUsed",
      null,
      [
        [1000, 610],
        [1000, 340],
      ],
    ],
    ["dieUsed", "endB", "Yes"],
    ["dieUsed", "jEventC", "No"],
  ],
);
