import { page } from "../page.js";

export default page(
  "Event",
  "EV",
  {
    start: ["S", 30, 10, 120, 60, "Event"],
    prefPlay: ["D", 20, 100, 140, 60, "Holding a *playable* *preferred* card"],
    prefPri: [
      "P",
      10,
      190,
      160,
      150,
      "Priority:",
      {
        items: [
          "*Full hand* with *preferred* card",
          "*Preferred* Event card",
          "*Preferred* Faction Event card",
          "Ascending order of initiative",
        ],
      },
    ],
    playA: ["A", 30, 370, 120, 60, "Play Event/Faction Event card"],
    eventDie: ["D", 190, 100, 120, 60, "Using an event die"],
    ret1: ["J", 350, 100, 120, 60, "Phase 5 - continue from where you came"],
    less4: [
      "d",
      190,
      190,
      120,
      60,
      "Holding less than 4 Event cards - excluding Faction Event cards",
    ],
    drawPref: ["A", 190, 280, 120, 60, "Draw a *preferred* Event card"],
    less3f: [
      "d",
      350,
      190,
      120,
      60,
      "Holding less than 3 Faction Event cards",
      { wome: true },
    ],
    drawFac: ["A", 350, 280, 120, 60, "Draw a Faction Event card"],
    anyPlay: [
      "d",
      510,
      190,
      120,
      60,
      "Holding a *playable* Event or Faction Event card",
    ],
    anyPri: [
      "P",
      485,
      280,
      170,
      120,
      "Priority:",
      {
        items: [
          "*Full hand*",
          "Event card",
          "Faction Event card",
          "Ascending order of initiative",
        ],
      },
    ],
    playB: ["A", 510, 430, 120, 60, "Play Event/Faction Event card"],
    drawPrefT: ["T", 670, 190, 120, 60, "Draw a *preferred* Event card"],
    aboveFull: ["d", 825, 190, 120, 60, "Above *full hand*"],
    discPri: [
      "P",
      800,
      280,
      170,
      130,
      "Priority:",
      {
        items: [
          "Not *preferred* card",
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile",
          "Descending order of initiative",
        ],
      },
    ],
    discard: ["A", 825, 440, 120, 60, "Discard"],
    endA: ["A", 1015, 190, 120, 60, "End action"],
    startDisc: ["S", 1015, 315, 120, 60, "Event card discard"],
    start2: ["S", 30, 490, 120, 60, "Event 2"],
    revCard: [
      "D",
      30,
      582,
      120,
      60,
      "Holding an “if Fellowship revealed” card",
    ],
    playC: ["A", 30, 672, 120, 60, "Play Event/Faction Event card"],
    corrCard: [
      "D",
      190,
      582,
      120,
      60,
      "Holding a card which can add corruption to the Fellowship or adds a Hunt tile",
    ],
    playD: ["A", 190, 672, 120, 60, "Play Event/Faction Event card"],
    less4b: [
      "D",
      350,
      582,
      120,
      60,
      "Holding less than 4 Event cards - excluding Faction Event cards",
    ],
    drawChar: ["A", 350, 672, 120, 60, "Draw a character Event card"],
    ret2: ["J", 510, 582, 120, 60, "Phase 5 - continue from where you came"],
    title: ["N", 1060, 10, 100, 60, "Event"],
  },
  [
    ["start", "prefPlay"],
    ["prefPlay", "prefPri", "Yes"],
    ["prefPlay", "eventDie", "No"],
    ["prefPri", "playA"],
    ["eventDie", "less4", "Yes"],
    ["eventDie", "ret1", "No"],
    ["less4", "drawPref", "Yes"],
    ["less4", "less3f", "No"],
    ["less3f", "drawFac", "Yes"],
    ["less3f", "anyPlay", "No"],
    ["anyPlay", "anyPri", "Yes"],
    ["anyPlay", "drawPrefT", "No"],
    ["anyPri", "playB"],
    ["drawPrefT", "aboveFull"],
    ["aboveFull", "endA", "No"],
    ["aboveFull", "discPri", "Yes"],
    ["discPri", "discard"],
    ["startDisc", "discPri"],
    ["start2", "revCard"],
    ["revCard", "playC", "Yes"],
    ["revCard", "corrCard", "No"],
    ["corrCard", "playD", "Yes"],
    ["corrCard", "less4b", "No"],
    ["less4b", "drawChar", "Yes"],
    ["less4b", "ret2", "No"],
  ],
);
