import { page } from "../page.js";

export default page(
  "Move/Recruit/Play/Draw Faction",
  "FA",
  {
    startPlay: ["S", 60, 10, 120, 60, "Play Faction Event"],
    playable: ["D", 60, 100, 120, 60, "Holding *playable* Faction Event card"],
    playPri: [
      "P",
      20,
      190,
      200,
      90,
      "Priority:",
      {
        items: [
          "*Preferred* card",
          "*Mobile* army attacks *target*",
          "Moves *mobile* army",
          "Muster",
        ],
      },
    ],
    playA: ["A", 60, 305, 120, 60, "Play Faction Event card"],
    startDraw: ["S", 270, 10, 120, 60, "Draw Faction Event"],
    blackSails: [
      "D",
      270,
      100,
      120,
      60,
      "Black Sails on table and Corsairs in play",
    ],
    corsairSiege: [
      "d",
      270,
      200,
      120,
      60,
      "One or more Corsairs could move to a siege",
    ],
    siegePri: [
      "P",
      250,
      300,
      160,
      70,
      "Priority:",
      { items: ["Siege", "Highest *value* army"] },
    ],
    moveC: ["A", 270, 405, 120, 60, "Move"],
    playDie: ["D", 430, 100, 120, 60, "Using Play Faction Event die"],
    ret: ["J", 430, 200, 120, 60, "Phase 5 - continue from where you came"],
    drawT: ["T", 590, 100, 120, 60, "Draw a Faction Event card"],
    aboveFull: ["D", 750, 100, 120, 60, "Above *full hand*"],
    discPri: [
      "P",
      730,
      190,
      160,
      120,
      "Priority:",
      {
        items: [
          "No faction picture",
          "Faction not in play",
          "Not *preferred* card",
          "Doesn't use the term “Fellowship revealed”",
          "Doesn't place a tile",
        ],
      },
    ],
    discard: ["A", 750, 345, 120, 60, "Discard"],
    end: ["A", 930, 100, 120, 60, "End"],
    startDisc: ["S", 930, 220, 120, 60, "Faction Event card discard"],
    startMove: ["S", 60, 440, 120, 60, "Move Faction"],
    figFs: ["D", 60, 530, 120, 60, "Faction figure in Fellowship region"],
    destA: [
      "P",
      40,
      620,
      160,
      70,
      "Destination priority:",
      { items: ["Nearest *mobile* army", "Highest *value* army"] },
    ],
    fsStrong: [
      "D",
      270,
      530,
      120,
      60,
      "Fellowship in a stronghold or out to sea",
    ],
    destB: [
      "P",
      230,
      620,
      200,
      100,
      "Destination priority:",
      {
        items: [
          "Fellowship progress region (nearest Faction figure only)",
          "Nearest *mobile* army",
          "Highest *value* army",
        ],
      },
    ],
    moveF: ["A", 270, 760, 120, 60, "Move"],
    destC: [
      "P",
      450,
      500,
      200,
      120,
      "Destination priority:",
      {
        items: [
          "Fellowship (nearest Faction figure only - two if one will be discarded)",
          "Nearest *mobile* army",
          "Highest *value* army",
        ],
      },
    ],
    startRecruit: ["S", 750, 430, 120, 60, "Recruit Faction"],
    recruitPri: [
      "P",
      680,
      525,
      260,
      95,
      "Priority:",
      {
        items: [
          "Faction with most *preferred* Faction Event cards in hand and in play",
          "Faction with most Faction Event cards in hand and in play",
        ],
      },
    ],
    eligible: [
      "D",
      985,
      542,
      120,
      60,
      "Faction eligible to be brought into play",
    ],
    musterFig: ["A", 985, 452, 120, 60, "Muster faction figures"],
    bringIn: ["A", 985, 632, 120, 60, "Bring faction into play"],
    title: ["N", 660, 10, 500, 60, "Move/Recruit/Play/Draw Faction"],
    note: ["N", 990, 60, 170, 20, "Warriors of Middle-Earth only"],
  },
  [
    ["startPlay", "playable"],
    ["playable", "playPri", "Yes"],
    ["playable", "blackSails", "No"],
    ["playPri", "playA"],
    ["startDraw", "blackSails"],
    ["blackSails", "corsairSiege", "Yes"],
    ["blackSails", "playDie", "No"],
    ["corsairSiege", "siegePri", "Yes"],
    ["corsairSiege", "playDie", "No"],
    ["siegePri", "moveC"],
    ["playDie", "ret", "Yes"],
    ["playDie", "drawT", "No"],
    ["drawT", "aboveFull"],
    ["aboveFull", "discPri", "Yes"],
    ["aboveFull", "end", "No"],
    ["discPri", "discard"],
    ["startDisc", "discPri"],
    ["startMove", "figFs"],
    ["figFs", "destA", "Yes"],
    ["figFs", "fsStrong", "No"],
    [
      "destA",
      "moveF",
      null,
      [
        [120, 740],
        [330, 740],
      ],
    ],
    ["fsStrong", "destB", "Yes"],
    ["fsStrong", "destC", "No"],
    ["destB", "moveF"],
    [
      "destC",
      "moveF",
      null,
      [
        [550, 740],
        [330, 740],
      ],
    ],
    ["startRecruit", "recruitPri"],
    ["recruitPri", "eligible"],
    ["eligible", "musterFig", "No"],
    ["eligible", "bringIn", "Yes"],
  ],
);
