import { page } from "../page.js";
import { threatColumn, threatEdges } from "./threat-column.js";

export default page(
  "Military Strategy Phase 5",
  "M5",
  Object.assign(threatColumn(), {
    p5: ["S", 10, 10, 120, 60, "Phase 5"],
    wkNotMob: [
      "D",
      240,
      90,
      130,
      80,
      "Witch King is in play and not in a *mobile* army",
      { bold: true },
    ],
    jChar2: ["J", 400, 310, 120, 60, "Character 2"],
    minion: [
      "D",
      400,
      85,
      120,
      90,
      "Conditions to muster a minion met",
      {
        bold: true,
        t2: "Southrons & Easterlings not at war or no faction recruited",
      },
    ],
    jMuster2: ["J", 400, 210, 120, 60, "Muster 2"],
    charMordor: [
      "D",
      560,
      100,
      120,
      60,
      "Character cards > 0 and Fellowship on Mordor track or revealed",
      { bold: true },
    ],
    revCard: [
      "d",
      560,
      190,
      120,
      60,
      "Holding a Fellowship revealed character card",
    ],
    playCharDie: [
      "A",
      560,
      290,
      120,
      60,
      "Play card using character die",
      { die: "Character" },
    ],
    playEventDie: [
      "A",
      560,
      380,
      120,
      60,
      "Play card using event die",
      { die: "Event" },
    ],
    mobAdjBlock: [
      "D",
      720,
      70,
      120,
      89,
      "*Mobile* army adjacent to *target* or an army which is *blocking* the route to *target*",
      { bold: true },
    ],
    anyCond: [
      "d",
      715,
      190,
      130,
      160,
      "ANY condition true:",
      {
        items: [
          "*Target* provides enough victory points to win",
          "*Target* is in a nation at war and not under siege",
          "Fellowship is in Mordor",
        ],
        any: true,
      },
    ],
    jArmy4c: ["J", 720, 380, 120, 60, "Army 4\n(character die)"],
    jArmy4: ["J", 880, 380, 120, 60, "Army 4"],
    playMuster: [
      "D",
      880,
      100,
      120,
      60,
      "*Playable* muster strategy cards > 0",
    ],
    jMuster3: ["J", 880, 10, 120, 60, "Muster 3 /\nMuster Event card"],
    pass: ["A", 1035, 100, 120, 60, "Pass"],
    jPlayFac: ["J", 1035, 190, 120, 60, "Play Faction Event", { wome: true }],
    jEvent: ["J", 400, 490, 120, 60, "Event"],
    mobAdjTgt: ["D", 560, 490, 120, 60, "*Mobile* army adjacent to *target*"],
    jArmy4c2: ["J", 560, 590, 120, 60, "Army 4\n(character die)"],
    jArmy4b: ["J", 720, 590, 120, 60, "Army 4"],
    jArmy3: ["J", 720, 490, 120, 60, "Army 3"],
    jChar: ["J", 880, 490, 120, 60, "Character"],
    jRecruit: ["J", 1035, 490, 120, 60, "Recruit Faction", { wome: true }],
    jMuster: ["J", 400, 690, 120, 60, "Muster"],
    jDrawFac: ["J", 560, 690, 120, 60, "Draw Faction Event", { wome: true }],
    jRing: [
      "J",
      720,
      690,
      120,
      60,
      "Phase 5\n(use a ring for any condition possible)",
    ],
    discardDie: ["A", 880, 690, 120, 60, "Discard unplayable die"],
    minionDie: ["A", 1035, 690, 120, 60, "Use Muster die set aside for minion"],
    title: ["N", 480, 10, 390, 60, "Military Strategy Phase 5"],
  }),
  threatEdges("wkNotMob", "wkNotMob").concat([
    [
      "wkNotMob",
      "jChar2",
      "Yes",
      [
        [330, 170],
        [330, 340],
      ],
    ],
    [
      "jChar2",
      "minion",
      null,
      [
        [460, 290],
        [380, 290],
        [380, 130],
      ],
    ],
    ["wkNotMob", "minion", "No"],
    ["minion", "jMuster2", "Yes"],
    ["jMuster2", "charMordor", null, [[540, 220]]],
    ["minion", "charMordor", "No"],
    ["charMordor", "revCard", "Yes"],
    ["charMordor", "mobAdjBlock", "No"],
    ["revCard", "playCharDie", "Yes"],
    ["revCard", "mobAdjBlock", "No"],
    ["playCharDie", "playEventDie"],
    ["playEventDie", "mobAdjBlock"],
    ["playCharDie", "mobAdjBlock"],
    ["mobAdjBlock", "anyCond", "Yes"],
    ["mobAdjBlock", "playMuster", "No"],
    ["anyCond", "jArmy4c", "Yes"],
    [
      "anyCond",
      "playMuster",
      null,
      [
        [860, 270],
        [860, 130],
      ],
    ],
    ["jArmy4c", "jArmy4"],
    ["jArmy4", "playMuster"],
    ["playMuster", "jMuster3", "Yes"],
    ["jMuster3", "pass"],
    ["playMuster", "pass", "No"],
    ["pass", "jPlayFac"],
    [
      "jPlayFac",
      "jEvent",
      null,
      [
        [1095, 460],
        [460, 460],
      ],
    ],
    ["jEvent", "mobAdjTgt"],
    ["mobAdjTgt", "jArmy4c2", "Yes"],
    ["mobAdjTgt", "jArmy3", "No"],
    ["jArmy4c2", "jArmy4b"],
    [
      "jArmy4b",
      "jArmy3",
      null,
      [
        [780, 570],
        [700, 570],
        [700, 520],
      ],
    ],
    ["jArmy3", "jChar"],
    ["jChar", "jRecruit"],
    [
      "jRecruit",
      "jMuster",
      null,
      [
        [1095, 670],
        [460, 670],
      ],
    ],
    ["jMuster", "jDrawFac"],
    ["jDrawFac", "jRing"],
    ["jRing", "discardDie"],
    ["discardDie", "minionDie"],
  ]),
);
