import { page } from "../page.js";

export default page(
  "Muster",
  "MU",
  {
    start: ["S", 10, 10, 120, 60, "Muster"],
    shThreat: [
      "D",
      10,
      100,
      120,
      60,
      "A stronghold is under *threat* and is able to muster",
    ],
    pEliteReg1: [
      "P",
      10,
      190,
      120,
      60,
      "*Primary* - Elite\n*Secondary* - Regular",
    ],
    start2: ["S", 210, 10, 120, 60, "Muster 2"],
    minion: ["D", 210, 100, 120, 60, "Able to recruit a minion"],
    wotw: [
      "d",
      170,
      190,
      200,
      70,
      "Free People have a Will of the West die and Gandalf the White has not been recruited and no minions have been recruited",
    ],
    saveDie: [
      "J",
      260,
      295,
      120,
      60,
      "Save muster for use as last die and return to Phase 5",
    ],
    minionPri: [
      "P",
      90,
      295,
      140,
      90,
      "Priority:",
      { items: ["Saruman", "Witch King", "Mouth of Sauron"] },
    ],
    musterMinion: ["A", 100, 421, 120, 60, "Muster"],
    notWar: [
      "D",
      410,
      100,
      120,
      60,
      "A Shadow nation is not at war or no faction is in play",
    ],
    nationPri: [
      "P",
      400,
      190,
      140,
      110,
      "Priority:",
      {
        items: ["Isengard", "Faction", "Sauron", "Southrons and Easterlings"],
      },
    ],
    facTop: [
      "d",
      410,
      330,
      120,
      60,
      "Faction was highest priority",
      { wome: true },
    ],
    polTrack: [
      "A",
      330,
      421,
      120,
      60,
      "Move nation down one on political track",
    ],
    jRecruit: ["J", 490, 421, 120, 60, "Recruit Faction", { wome: true }],
    start3: ["S", 610, 10, 120, 60, "Muster 3/Muster Event card"],
    musterCard: ["D", 610, 100, 120, 60, "Holding a *playable* muster card"],
    cardChoice: [
      "d",
      610,
      190,
      120,
      60,
      "Card allows choice of muster location",
    ],
    musterCardA: ["A", 610, 280, 120, 60, "Muster"],
    canMuster: ["D", 810, 100, 120, 60, "Shadow is able to muster"],
    ret: ["J", 1010, 100, 120, 60, "Phase 5 - continue from where you came"],
    exposedC: ["d", 810, 190, 120, 60, "Able to create an *exposed* *target*"],
    pEliteReg2: [
      "P",
      1010,
      190,
      120,
      60,
      "*Primary* - Elite\n*Secondary* - Regular",
    ],
    musterE: ["A", 1010, 280, 120, 60, "Muster"],
    fsAdj: [
      "d",
      805,
      347,
      130,
      110,
      "Fellowship adjacent to Shadow settlement and Fellowship Progress puts it outside Mordor and no army is in or adjacent to its region",
    ],
    pRegNaz: [
      "P",
      970,
      362,
      120,
      80,
      "*Primary* - Regular\n*Secondary* - Nazgûl",
    ],
    armyRegion: [
      "d",
      610,
      528,
      120,
      60,
      "Muster possible in region containing a Shadow army",
    ],
    startMoS: ["S", 770, 528, 120, 60, "Muster Mouth of Sauron"],
    armyPri: [
      "P",
      580,
      620,
      180,
      98,
      "Priority:",
      {
        items: [
          "Conducting a siege",
          "*Mobile* army",
          "Would become *mobile*",
          "Contains Saruman",
          "Highest *value*",
        ],
      },
    ],
    pEliteReg3: [
      "P",
      810,
      639,
      120,
      60,
      "*Primary* - Elite\n*Secondary* - Regular",
    ],
    settlePri: [
      "P",
      390,
      512,
      180,
      92,
      "Settlement closest to:",
      {
        items: [
          "*Target* in nation at war",
          "*Target* in active nation",
          "*Mobile* army",
          "*Target* in passive nation",
        ],
      },
    ],
    sixNaz: ["d", 240, 528, 120, 60, "Less than six Nazgûl in play"],
    pEliteNaz: [
      "P",
      160,
      638,
      120,
      60,
      "*Primary* - Elite\n*Secondary* - Nazgûl",
    ],
    pNazNaz: [
      "P",
      320,
      638,
      120,
      60,
      "*Primary* - Nazgûl\n*Secondary* - Nazgûl",
    ],
    musterEnd: ["A", 524, 750, 120, 60, "Muster"],
    title: ["N", 1040, 10, 120, 60, "Muster"],
  },
  [
    ["start", "shThreat"],
    ["shThreat", "pEliteReg1", "Yes"],
    ["shThreat", "minion", "No"],
    [
      "pEliteReg1",
      "musterEnd",
      null,
      [
        [70, 730],
        [585, 730],
      ],
    ],
    ["start2", "minion"],
    ["minion", "wotw", "Yes"],
    ["minion", "notWar", "No"],
    ["wotw", "saveDie", "Yes", null, { ex: [0.75, 1], en: [0.5, 0] }],
    [
      "wotw",
      "minionPri",
      "No",
      [
        [220, 280],
        [160, 280],
      ],
    ],
    ["minionPri", "musterMinion"],
    ["notWar", "nationPri", "Yes"],
    ["notWar", "musterCard", "No"],
    ["nationPri", "facTop"],
    ["facTop", "jRecruit", "Yes", null, { ex: [1, 0.5], en: [0.5, 0] }],
    ["facTop", "polTrack", "No", null, { ex: [0, 0.5], en: [0.5, 0] }],
    ["start3", "musterCard"],
    ["musterCard", "cardChoice", "Yes"],
    ["musterCard", "canMuster", "No"],
    ["cardChoice", "exposedC", "Yes"],
    ["cardChoice", "musterCardA", "No"],
    ["canMuster", "exposedC", "Yes"],
    ["canMuster", "ret", "No"],
    ["exposedC", "pEliteReg2", "Yes"],
    ["exposedC", "fsAdj", "No"],
    ["pEliteReg2", "musterE"],
    ["fsAdj", "pRegNaz", "Yes"],
    ["fsAdj", "armyRegion", "No"],
    [
      "pRegNaz",
      "musterEnd",
      null,
      [
        [1030, 730],
        [585, 730],
      ],
    ],
    ["startMoS", "armyRegion"],
    ["armyRegion", "armyPri", "Yes"],
    ["armyRegion", "settlePri", "No"],
    ["armyPri", "pEliteReg3"],
    [
      "pEliteReg3",
      "musterEnd",
      null,
      [
        [870, 730],
        [585, 730],
      ],
    ],
    ["settlePri", "sixNaz"],
    ["sixNaz", "pEliteNaz", "No"],
    ["sixNaz", "pNazNaz", "Yes"],
    [
      "pNazNaz",
      "musterEnd",
      null,
      [
        [380, 730],
        [585, 730],
      ],
    ],
    [
      "pEliteNaz",
      "musterEnd",
      null,
      [
        [220, 730],
        [585, 730],
      ],
    ],
  ],
);
