// The left-hand "threat/exposed" column both Phase 5 pages share: its boxes (threatColumn) and its arrows (threatEdges,
// with the ids of the boxes the No arrows of its two exits lead to).
export function threatColumn() {
  return {
    threat: [
      "D",
      10,
      100,
      120,
      60,
      "Shadow under *threat* or Free People *exposed*",
      { bold: true },
    ],
    mobAdjThreat: ["d", 10, 190, 120, 60, "*Mobile* army adjacent to *threat*"],
    atkChar: [
      "A",
      170,
      190,
      120,
      60,
      "Attack using character die",
      { die: "Character" },
    ],
    atkArmy: ["A", 170, 280, 120, 60, "Attack using army die", { die: "Army" }],
    createMob: [
      "d",
      10,
      280,
      120,
      60,
      "Move can create *mobile* army adjacent to *threat*",
    ],
    incTroops: [
      "d",
      10,
      370,
      120,
      60,
      "Move can increase troop numbers in the Stronghold under *threat*",
    ],
    moveChar: [
      "A",
      170,
      370,
      120,
      60,
      "Move using character die",
      { die: "Character" },
    ],
    routeThreat: [
      "d",
      10,
      460,
      120,
      60,
      "*Mobile* army’s route to closest *target* takes it towards *threat*",
    ],
    jArmyT: ["J", 170, 460, 120, 60, "Army"],
    shValid: [
      "d",
      10,
      550,
      120,
      60,
      "Stronghold under *threat* is valid for muster",
    ],
    jMusterT: ["J", 170, 550, 120, 60, "Muster"],
    sieging: [
      "d",
      10,
      640,
      120,
      60,
      "*Threat* is sieging a Shadow stronghold which can use more leadership",
    ],
    jChar3: ["J", 170, 640, 120, 60, "Character 3 /\nMuster Witch King"],
    toExposed: ["d", 10, 730, 120, 60, "Can move towards *exposed*"],
    jArmyE: ["J", 170, 730, 120, 60, "Army"],
    ringNote: [
      "N",
      150,
      20,
      220,
      40,
      "bold text indicates a ring should be used where the condition is met and the required die is unavailable",
    ],
  };
}
export function threatEdges(exitNo, exitEnd) {
  return [
    ["p5", "threat"],
    ["threat", "mobAdjThreat", "Yes"],
    ["threat", exitNo, "No"],
    ["mobAdjThreat", "atkChar", "Yes"],
    ["mobAdjThreat", "createMob", "No"],
    ["atkChar", "atkArmy"],
    ["atkArmy", "createMob"],
    ["createMob", "moveChar", "Yes"],
    ["createMob", "incTroops", "No"],
    ["incTroops", "moveChar", "Yes"],
    ["incTroops", "routeThreat", "No"],
    ["routeThreat", "moveChar", "Yes"],
    ["routeThreat", "shValid", "No"],
    ["moveChar", "jArmyT"],
    [
      "jArmyT",
      "shValid",
      null,
      [
        [230, 530],
        [70, 530],
      ],
    ],
    ["shValid", "jMusterT", "Yes"],
    ["shValid", "sieging", "No"],
    [
      "jMusterT",
      "sieging",
      null,
      [
        [230, 620],
        [70, 620],
      ],
    ],
    ["sieging", "jChar3", "Yes"],
    ["sieging", "toExposed", "No"],
    [
      "jChar3",
      "toExposed",
      null,
      [
        [230, 710],
        [70, 710],
      ],
    ],
    ["toExposed", "jArmyE", "Yes"],
    [
      "toExposed",
      exitEnd,
      "No",
      [
        [150, 810],
        [310, 480],
      ],
    ],
    ["jArmyE", exitEnd, null, [[310, 460]]],
  ];
}
