// Shadow card data — transcribed from claude/wotr_shadow_cards_and_dice.json (project doc).
// Fields: id, set, deck (C=Character, S=Strategy, F=Faction Event, B=Call to Battle),
// type (die that plays it: Character/Army/Muster), title, cond, text, ct (combat title), cc (combat cond), ctext, init, faction.
// Behaviour flags (read by engine.js — never derived from the card text):
//  onTable      the card stays on the table when played as an event
//  revealed     event half needs the Fellowship revealed ("uses the term Fellowship revealed" in the priority lists)
//  tile         places or draws a Hunt tile (the special-tile cards count as placing one)
//  corruption   event half can add Corruption
//  pre          key into PRECONDITIONS in engine.js (board fact the event half needs; situational keys are asked once per turn)
//  cpre         key into COMBAT_PRECONDITIONS (battle-form fact the combat half or Call to Battle card needs)
//  effect       hand/dice effect the engine resolves itself: servants | hisWill | lidlessEye | recruitFaction
//  tableCombat  may be discarded from the table to use its combat half (Balrog of Moria)
//  reminder     shown under the card in the "On the table" list
window.QB_CARDS = [
{id:"sa001b2",set:"2E",deck:"C",type:"Character",title:"Balrog of Moria",cond:"Play on the table.",text:"You may discard \"Balrog of Moria\" to draw an additional Hunt tile if the Fellowship moves into, out of, or through Moria while being declared or revealed. If the tile shows an Eye, discard it without effect; otherwise follow the rules for a successful Hunt.\n\nIgnore any \"Reveal\" icon on the drawn tile if the Fellowship has been declared in a Free Peoples City or Stronghold.\n\nOr, you may discard \"Balrog of Moria\" to use its Combat card effect as if you were playing the card from your hand.",ct:"Durin's Bane",cc:"Play if the defending Army is within two regions of Moria.",ctext:"Before the Combat Roll, roll an additional attack using three Combat dice. Score hits on 4+ and apply the result immediately.",init:2,onTable:true,tile:true,cpre:"nearMoria",tableCombat:true,reminder:"Discard it to draw an extra Hunt tile when the Fellowship moves into, out of or through Moria while declared or revealed. In a battle within two regions of Moria the Battle page offers it as Durin’s Bane."},
{id:"sa002",set:"2E",deck:"S",type:"Muster",title:"A New Power Is Rising",cond:"Play if Saruman is in play.",text:"Recruit two Isengard Regular units in each of North and South Dunland and two Isengard units (Regular or Elite) in Orthanc.",ct:"Great Host",cc:null,ctext:"If, after removing casualties from the Combat roll and Leader re-roll, your Army units are at least twice as many as the enemy Army units, score one automatic hit.",init:7,pre:"saruman"},
{id:"sa003",set:"2E",deck:"C",type:"Character",title:"Candles of Corpses",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Roll three dice and add one Corruption point on each result of 4+.\n\nIf Gollum is the Guide, add one Corruption point on each result of '6' instead.",ct:"Dread and Despair",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\n\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.",init:3,corruption:true,pre:"fsNotInFPSettlement",cpre:"nazLead1"},
{id:"sa005",set:"2E",deck:"C",type:"Character",title:"Cruel Weather",cond:"Play if the Fellowship is on step 1 or higher on the Fellowship Track.",text:"Move the Fellowship to an adjacent region.",ct:"Cruel as Death",cc:"Play if the total Nazgûl Leadership is 2 or more.",ctext:"Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.",init:3,pre:"fsProgress1",cpre:"nazLead2"},
{id:"sa007",set:"2E",deck:"S",type:"Army",title:"Denethor's Folly",cond:"Play on the table if Minas Tirith is under siege by a Shadow Army.",text:"When you play this card, immediately eliminate one Free Peoples Leader in Minas Tirith.\n\nWhen \"Denethor's Folly\" is in play, the Free Peoples player cannot use Combat cards for battles fought in Minas Tirith.\n\nThe Free Peoples player can force \"Denethor's Folly\" to be discarded using a Will of the West Action die result, or any Action die result if Gandalf or Aragorn is in Minas Tirith.",ct:"Devilry of Orthanc",cc:"Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.",ctext:"Add 1 to all dice on your Combat roll.",init:3,onTable:true,pre:"mtSiege",cpre:"isengardStronghold",reminder:"The Free Peoples player can force its discard with a Will of the West die, or any die if Gandalf or Aragorn is in Minas Tirith — press Discard when that happens."},
{id:"sa008",set:"2E",deck:"C",type:"Character",title:"Dreadful Spells",cond:"Play if a Shadow Army containing Nazgûl is adjacent to, or is in the same region as, a Free Peoples Army.",text:"Roll a number of dice equal to the number of Nazgûl (up to a maximum of 5) and score one hit for every result of 5+.",ct:"Devilry of Orthanc",cc:"Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.",ctext:"Add 1 to all dice on your Combat roll.",init:3,pre:"nazNearFP",cpre:"isengardStronghold"},
{id:"sa009",set:"2E",deck:"C",type:"Character",title:"Flocks of Crebain",cond:"Play on the table.",text:"Before you make a Hunt roll, you may discard \"Flocks of Crebain\" to add 1 to all dice on that Hunt roll (including re-rolls).\n\nYou must discard this card from the table immediately if the Fellowship is declared in an unconquered Free Peoples City or Stronghold.",ct:"They are Terrible",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.",init:4,onTable:true,cpre:"nazLead1",reminder:"Discard it before a Hunt roll to add 1 to all dice on that roll (including re-rolls). The app asks whether to discard it when the tracker shows the Fellowship revealed in a Free Peoples settlement."},
{id:"sa010",set:"2E",deck:"C",type:"Character",title:"Foul Thing from the Deep",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Draw a Hunt tile.\n\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\n\nOtherwise, follow the rules for a successful Hunt, except that the Free Peoples player must reduce Hunt Damage (if any) by eliminating a random Companion (unless there are no Companions in the Fellowship) before using the Ring.",ct:"They are Terrible",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.",init:4,tile:true,pre:"fsNotInFPSettlement",cpre:"nazLead1"},
{id:"sa011",set:"2E",deck:"C",type:"Character",title:"Give It to Uss!",cond:null,text:"The \"Give it to Uss!\" special Hunt tile is now in play.\n\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.",ct:"One for the Dark Lord",cc:"Play if the defending Army is in the same region as the Fellowship.",ctext:"Add 1 to all dice on your Combat roll and Leader re-roll.",init:3,tile:true,cpre:"defInFs"},
{id:"sa012",set:"2E",deck:"C",type:"Character",title:"Grond, Hammer of the Underworld",cond:"Play if the Witch-King is in play and is with a Shadow Army besieging a Stronghold.",text:"Attack that Stronghold. The siege lasts for three Combat rounds instead of one. During the first round, the Free Peoples player cannot use a Combat card unless a Companion is in the battle.",ct:"Dread and Despair",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\n\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.",init:3,pre:"wkBesieging",cpre:"nazLead1"},
{id:"sa013",set:"2E",deck:"S",type:"Army",title:"Half-orcs and Goblin-men",cond:"Play if Isengard is \"At War.\"",text:"Recruit one Isengard unit (Regular or Elite) in a region where a Shadow Army is present.",ct:"We Come to Kill",cc:"Play if a Shadow Elite unit is in the battle.",ctext:"After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.",init:7,pre:"isengardAtWar",cpre:"shadowElite"},
{id:"sa014",set:"2E",deck:"S",type:"Army",title:"Hill-trolls",cond:"Play if Sauron is \"At War.\"",text:"Replace two Sauron Regular units anywhere on the game board with two Sauron Elite units.",ct:"We Come to Kill",cc:"Play if a Shadow Elite unit is in the battle.",ctext:"After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.",init:7,pre:"sauronAtWar",cpre:"shadowElite"},
{id:"sa015",set:"2E",deck:"S",type:"Muster",title:"Horde From the East",cond:"Play if the Southrons & Easterlings are \"At War\".",text:"Recruit five Southron & Easterling Regular units in a free region inside the Southron and Easterling Nation. This region must be adjacent to the eastern edge of the map.",ct:"Deadly Strife",cc:null,ctext:"Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",init:3,pre:"seAtWar"},
{id:"sa016",set:"2E",deck:"C",type:"Character",title:"Isildur's Bane",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Draw a Hunt tile.\n\nIf the tile shows an Eye or is a Fellowship special tile, discard it without effect.\n\nOtherwise, follow the rules for a successful Hunt, except that Hunt Damage may not be reduced in any way before using the Ring.",ct:"Cruel as Death",cc:"Play if the total Nazgûl Leadership is 2 or more.",ctext:"Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.",init:3,tile:true,pre:"fsNotInFPSettlement",cpre:"nazLead2"},
{id:"sa017",set:"2E",deck:"C",type:"Character",title:"Lure of the Ring",cond:"Play if the Fellowship is revealed.",text:"Randomly select one Companion in the Fellowship by drawing a Companion counter.\n\nThe Free Peoples player must choose either to add Corruption equal to the Companion's Level, or to eliminate him.\n\nIf Gollum is the Guide, add one Corruption point instead.",ct:"They are Terrible",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Forfeit one point of Nazgûl Leadership to add 1 to all dice on your Leader re-roll.",init:4,revealed:true,corruption:true,pre:"fsRevealed",cpre:"nazLead1"},
{id:"sa018",set:"2E",deck:"S",type:"Muster",title:"Many Kings to the Service of Mordor",cond:null,text:"Recruit two Southron & Easterling Regular units in each of three different Southron & Easterling Settlements.",ct:"Great Host",cc:null,ctext:"If, after removing casualties from the Combat roll and Leader re-roll, your Army units are at least twice as many as the enemy Army units, score one automatic hit.",init:7,},
{id:"sa019",set:"2E",deck:"S",type:"Muster",title:"Monsters Roused",cond:null,text:"Recruit one Sauron Regular unit in each of Angmar, Ettenmoors and Weather Hills, and one Sauron Elite unit in Trollshaws.",ct:"Desperate Battle",cc:null,ctext:"Both Armies add 1 to all dice on their Combat roll and Leader re-roll.",init:3,},
{id:"sa020",set:"2E",deck:"C",type:"Character",title:"Morgul Wound",cond:"Play if the Fellowship is revealed.",text:"If the Fellowship's current Corruption is three or less, add two Corruption points, otherwise add one Corruption point.",ct:"Black Breath",cc:"Play if a Nazgûl is in the battle.",ctext:"If your Leader re-roll scores at least one hit, you may additionally eliminate one Free Peoples Leader participating in the battle. Alternatively, you can choose to eliminate a Companion in the battle, if the number of hits equals or exceeds the Companion's Level.",init:6,revealed:true,corruption:true,pre:"fsRevealed",cpre:"nazInBattle"},
{id:"sa021",set:"2E",deck:"S",type:"Muster",title:"Musterings of Long-planned War",cond:"Play if all Shadow Nations are \"At War.\"",text:"Recruit five Southron & Easterling Regular units in Gorgoroth and five Sauron Regular units in Nurn.",ct:"Desperate Battle",cc:null,ctext:"Both Armies add 1 to all dice on their Combat roll and Leader re-roll.",init:3,pre:"allAtWar"},
{id:"sa022",set:"2E",deck:"C",type:"Character",title:"Nazgûl Search",cond:"Play if the Fellowship is on step 1 or higher on the Fellowship Track.",text:"Move any or all of the Nazgûl.\n\nThen, if at least one Nazgûl is in the region with the Fellowship, the Fellowship is revealed.",ct:"Foul Stench",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.",init:3,pre:"fsProgress1",cpre:"nazLead1"},
{id:"sa023",set:"2E",deck:"S",type:"Army",title:"Olog-hai",cond:"Play if Sauron is \"At War.\"",text:"Recruit one Sauron unit (Regular or Elite) in a region where a Shadow Army is present.",ct:"We Come to Kill",cc:"Play if a Shadow Elite unit is in the battle.",ctext:"After removing casualties from the Combat roll and Leader re-roll, roll an additional attack using only the Shadow Elite units (up to a maximum of five) and score one hit for each result of 5+.",init:7,pre:"sauronAtWar",cpre:"shadowElite"},
{id:"sa024",set:"2E",deck:"C",type:"Character",title:"On, On They Went",cond:null,text:"The \"On, On They Went\" special Hunt tile is now in play.\n\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.",ct:"One for the Dark Lord",cc:"Play if the defending Army is in the same region as the Fellowship.",ctext:"Add 1 to all dice on your Combat roll and Leader re-roll.",init:3,tile:true,cpre:"defInFs"},
{id:"sa025",set:"2E",deck:"C",type:"Character",title:"Orc Patrol",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Draw a Hunt tile.\n\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\n\nOtherwise, follow the rules for a successful Hunt.",ct:"Cruel as Death",cc:"Play if the total Nazgûl Leadership is 2 or more.",ctext:"Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.",init:3,tile:true,pre:"fsNotInFPSettlement",cpre:"nazLead2"},
{id:"sa026",set:"2E",deck:"S",type:"Muster",title:"Orcs Multiplying Again",cond:null,text:"Recruit three Sauron Regular units in Dol Guldur and three Sauron Regular units in Mount Gundabad.",ct:"Onslaught",cc:null,ctext:"After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.",init:7,},
{id:"sa027",set:"2E",deck:"S",type:"Muster",title:"Pits of Mordor",cond:"Play if Sauron is \"At War.\"",text:"Recruit two Sauron Regular units in each of three different Sauron Strongholds.",ct:"Desperate Battle",cc:null,ctext:"Both Armies add 1 to all dice on their Combat roll and Leader re-roll.",init:3,pre:"sauronAtWar"},
{id:"sa028b2",set:"2E",deck:"S",type:"Muster",title:"Rage of the Dunlendings",cond:"Play if Isengard is \"At War\".",text:"Recruit two Isengard Regular units in a free region adjacent to North or South Dunland.\n\nYou may also move to this region up to four Isengard units (Regular or Elite) from North Dunland and/or South Dunland.",ct:"Relentless Assault",cc:null,ctext:"Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",init:3,pre:"isengardAtWar"},
{id:"sa028",set:"WoME-rev",deck:"S",type:"Muster",title:"Rage of the Dunlendings",cond:"Play if the Hillmen of Dunland faction is in play.",text:"Recruit up to four Dunlendings and add them to a Shadow Army in either North or South Dunland (respecting the stacking limit). You may then move or attack with that Army.",ct:"Relentless Assault",cc:null,ctext:"Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",init:3,faction:"Dunlendings",pre:"dunlendings"},
{id:"sa029",set:"2E",deck:"S",type:"Muster",title:"Return of the Witch-king",cond:"Play if the Witch-king is in play.",text:"Move the Witch-king to Angmar and recruit two Sauron Regular units and one Sauron Elite unit there.",ct:"Swarm of Bats",cc:null,ctext:"Cancel the effects of the Combat Card played by the Free Peoples player.\n\nIf the Free Peoples player did not play a card, add 1 to all dice on your Leader re-roll.",init:0,pre:"witchKing"},
{id:"sa030",set:"2E",deck:"S",type:"Army",title:"Return to Valinor",cond:"Play if you control at least one Elven Stronghold.",text:"For each region with an Elven Stronghold which is not under siege, roll a number of dice equal to the number of Elven Army units in that region (up to a maximum of 5) and score one hit against that army for each result of '6.'",ct:"Deadly Strife",cc:null,ctext:"Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",init:3,pre:"elvenStronghold"},
{id:"sa032",set:"2E",deck:"S",type:"Army",title:"Shadows Gather",cond:null,text:"Move one Shadow Army up to three regions: the movement must end in a region already occupied by another Shadow Army (that must not be under siege). The traversed regions must be free for the purposes of Army movement, and no Shadow units may be picked up or dropped off along the way (other than, possibly, splitting the Army initially).",ct:"Mûmakil",cc:"Play if a Southrons & Easterlings Elite unit is in the battle.",ctext:"Add 1 to all dice on your Combat roll. If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-Combat attack from a Combat card), score one additional hit.",init:"3-5",cpre:"seElite"},
{id:"sa033",set:"2E",deck:"S",type:"Muster",title:"Shadows on the Misty Mountains",cond:null,text:"Recruit two Sauron units (Regular or Elite) and one Nazgûl either in Mount Gram or in Moria.",ct:"Onslaught",cc:null,ctext:"After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.",init:7,},
{id:"sa034",set:"2E",deck:"C",type:"Character",title:"Shelob's Lair",cond:null,text:"The \"Shelob's Lair\" special Hunt tile is now in play.\n\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.",ct:"One for the Dark Lord",cc:"Play if the defending Army is in the same region as the Fellowship.",ctext:"Add 1 to all dice on your Combat roll and Leader re-roll.",init:3,tile:true,cpre:"defInFs"},
{id:"sa035",set:"2E",deck:"S",type:"Muster",title:"Stormcrow",cond:"Play if either the Fellowship or a Companion is inside the borders of a Free Peoples Nation not \"At War.\"",text:"Move that Nation's Political Counter back one step on the Political Track.\n\nThen, the Free Peoples player must eliminate one Leader or Army unit of that Nation (Regular or Elite).",ct:"Great Host",cc:null,ctext:"If, after removing casualties from the Combat roll and Leader re-roll, your Army units are at least twice as many as the enemy Army units, score one automatic hit.",init:7,pre:"fpNotWar"},
{id:"sa036",set:"2E",deck:"C",type:"Character",title:"The Black Captain Commands",cond:"Play if the Witch-king is in play.",text:"You may either recruit two Nazgûl in the region containing the Witch-king, or move any or all of the Nazgûl.\n\nThen, you may move or attack with an Army containing the Witch-king.",ct:"Foul Stench",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.",init:3,pre:"witchKing",cpre:"nazLead1"},
{id:"sa037",set:"2E",deck:"C",type:"Character",title:"The Breaking of the Fellowship",cond:"Play if the Fellowship is revealed.",text:"Draw a Hunt tile.\n\nIf the tile shows an Eye or is a Fellowship Special tile, discard it without effect.\n\nOtherwise, the Free Peoples player must separate a number of Companions equal to the number on the tile (if possible), placing them in the same region as the Fellowship. Ignore any \"Reveal\" or \"Stop\" icons on the tile.\n\nIf Gollum is the Guide, add one Corruption point instead.",ct:"Dread and Despair",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"Before the Combat roll, forfeit one or more points of Nazgûl Leadership.\n\nDuring his Combat roll, the Free Peoples player rolls one Combat die less (to a minimum of one) for every point you have chosen to forfeit.",init:3,revealed:true,tile:true,corruption:true,pre:"fsRevealed",cpre:"nazLead1"},
{id:"sa038b2",set:"2E",deck:"S",type:"Army",title:"Corsairs of Umbar",cond:"Play if the Southrons & Easterlings are \"At War\".",text:"Move one Shadow Army from Umbar to a Gondor coastal region.\n\nIf there is a Free Peoples Army in the region, a battle starts. The attacking Shadow Army cannot cease the attack, unless the Free Peoples Army was already under siege.",ct:"Deadly Strife",cc:null,ctext:"Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",init:3,pre:"seAtWar"},
{id:"sa038",set:"WoME-rev",deck:"S",type:"Army",title:"The Corsairs Are Upon Us!",cond:"Play if the Corsairs of Umbar faction is in play.",text:"You may move any or all of the Ships. Then, you may move one Army from a region containing a Ship to a region free for the purposes of Army movement which also contains a Ship.\n\nYou may then move or attack with that Army.\n\nIf a battle starts, during the first round the Free Peoples player cannot play a Combat Card.",ct:"Deadly Strife",cc:null,ctext:"Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",init:3,faction:"Corsairs",pre:"corsairs"},
{id:"sa039",set:"2E",deck:"S",type:"Army",title:"The Day Without Dawn",cond:"Play if all Shadow Nations are \"At War\".",text:"Discard all unused Free Peoples Action dice that show a Will of the West result.",ct:"Relentless Assault",cc:null,ctext:"Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",init:3,pre:"allAtWar"},
{id:"sa040",set:"2E",deck:"S",type:"Army",title:"The Fighting Uruk-hai",cond:"Play if Saruman is in play, and if an Army containing an Isengard unit is besieging a Stronghold.",text:"Attack that Stronghold. The siege lasts for three Combat rounds instead of one. During the first round, the Free Peoples player cannot use a Combat card unless a Companion is in the battle.",ct:"Onslaught",cc:null,ctext:"After removing casualties from the Combat roll and Leader re-roll, you may inflict and apply up to four additional hits against your units. Roll one die for each hit you inflicted to your units and score one hit against the enemy on each result of 4+.",init:7,pre:"isenBesieging"},
{id:"sa042",set:"2E",deck:"S",type:"Muster",title:"The King is Revealed",cond:"Play if Aragorn is in play.",text:"Recruit five Sauron Regular units and a Nazgûl in Minas Morgul.",ct:"Relentless Assault",cc:null,ctext:"Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",init:3,pre:"aragorn"},
{id:"sa043",set:"2E",deck:"C",type:"Character",title:"The Lidless Eye",cond:null,text:"Change up to three unused Shadow Action Dice results into \"Eye\" results.\n\nPlace these dice in the Hunt Box immediately.",ct:"Words of Power",cc:"Play if a Nazgûl is in the battle.",ctext:"Choose a Companion. That Companion's Leadership and special abilities are cancelled for this Combat round.",init:1,pre:"unusedDice",cpre:"nazInBattle",effect:"lidlessEye"},
{id:"sa044",set:"2E",deck:"C",type:"Character",title:"The Nazgûl Strike",cond:"Play if the Fellowship is on step 1 or higher on the Fellowship Track.",text:"Move any or all of the Nazgûl.\n\nThen, if at least one Nazgûl is in the region with the Fellowship, you may either discard one Free Peoples Character Event card from the table or roll for the Hunt (as if the Free Peoples player had moved the Fellowship).",ct:"Black Breath",cc:"Play if a Nazgûl is in the battle.",ctext:"If your Leader re-roll scores at least one hit, you may additionally eliminate one Free Peoples Leader participating in the battle. Alternatively, you can choose to eliminate a Companion in the battle, if the number of hits equals or exceeds the Companion's Level.",init:6,pre:"fsProgress1",cpre:"nazInBattle"},
{id:"sa045",set:"2E",deck:"C",type:"Character",title:"The Palantír of Orthanc",cond:"Play on the table if Saruman is in play.",text:"When \"The Palantír of Orthanc\" is in play, after you use an Event Action die result to play an Event card, immediately draw another card from either one of your decks.\n\nThe Free Peoples player can force \"The Palantír of Orthanc\" to be discarded by either using a Will of the West Action die result, or using any Action die result and one Elven Ring. You must discard this card if Saruman is eliminated.",ct:"Cruel as Death",cc:"Play if the total Nazgûl Leadership is 2 or more.",ctext:"Forfeit two points of Nazgûl Leadership to add 1 to all dice on your Combat roll.",init:3,onTable:true,pre:"saruman",cpre:"nazLead2",reminder:"Draws a card automatically after an Event die plays an Event card. Discarded automatically if Saruman is unticked; the Free Peoples player can force its discard with a Will of the West die, or any die plus an Elven Ring."},
{id:"sa046",set:"2E",deck:"C",type:"Character",title:"The Ring is Mine!",cond:null,text:"The \"The Ring Is Mine!\" special Hunt tile is now in play.\n\nAdd the tile to the Hunt Pool when the Fellowship is on the Mordor Track.",ct:"One for the Dark Lord",cc:"Play if the defending Army is in the same region as the Fellowship.",ctext:"Add 1 to all dice on your Combat roll and Leader re-roll.",init:3,tile:true,cpre:"defInFs"},
{id:"sa047",set:"2E",deck:"C",type:"Character",title:"The Ringwraiths are Abroad",cond:null,text:"Move any or all of the Nazgûl.\n\nThen, you may either move two Armies each containing a Nazgûl, or attack with one Army containing a Nazgûl.",ct:"Words of Power",cc:"Play if a Nazgûl is in the battle.",ctext:"Choose a Companion. That Companion's Leadership and special abilities are cancelled for this Combat round.",init:1,cpre:"nazInBattle"},
{id:"sa048",set:"2E",deck:"S",type:"Army",title:"The Shadow is Moving",cond:"Play if all Shadow Nations are \"At War.\"",text:"Move up to four different Shadow Armies one region each.",ct:"Swarm of Bats",cc:null,ctext:"Cancel the effects of the Combat card played by the Free Peoples player.\n\nIf the Free Peoples player did not play a card, add 1 to all dice on your Leader re-roll.",init:0,pre:"allAtWar"},
{id:"sa049",set:"2E",deck:"S",type:"Army",title:"The Shadow Lengthens",cond:null,text:"Move two Shadow Armies up to two regions: each movement must end in a region already occupied by another Shadow Army (that must not be under siege). The traversed regions must be free for the purposes of Army movement, and no Shadow units may be picked up or dropped off along the way (other than, possibly, splitting the Army initially).",ct:"Mûmakil",cc:"Play if a Southrons & Easterlings Elite unit is in the battle.",ctext:"Add 1 to all dice on your Combat roll. If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-Combat attack from a Combat card), score one additional hit.",init:"3-5",cpre:"seElite"},
{id:"sa050",set:"2E",deck:"S",type:"Muster",title:"Threats and Promises",cond:"Play on the table.",text:"When \"Threats and Promises\" is in play, the Free Peoples player cannot advance a passive Nation on the Political Track using a Muster Action die result.\n\nYou must discard this card from the table as soon as a Free Peoples Nation advances on the Political Track either due to an attack or due to a Companion's special ability.",ct:"Devilry of Orthanc",cc:"Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.",ctext:"Add 1 to all dice on your Combat roll.",init:3,onTable:true,cpre:"isengardStronghold",reminder:"Discarded automatically when a Free Peoples nation in the tracker advances from passive; when a nation goes to war the app asks whether an attack or a Companion caused it."},
{id:"sa051",set:"2E",deck:"C",type:"Character",title:"Wormtongue",cond:"Play on the table if Saruman is in play.",text:"When \"Wormtongue\" is in play, Rohan cannot be activated except by an appropriate Companion, or by the Fellowship being declared in Edoras or Helm's Deep, or by an attack on Edoras or Helm's Deep.\n\nYou must discard this card from the table as soon as Rohan is activated, or if Saruman is eliminated.",ct:"Foul Stench",cc:"Play if the total Nazgûl Leadership is 1 or more.",ctext:"If the Nazgûl Leadership equals or exceeds the total Free Peoples Leadership, the Free Peoples Leader re-roll is cancelled.",init:3,onTable:true,pre:"saruman",cpre:"nazLead1",reminder:"Discarded automatically when Rohan leaves passive in the tracker or Saruman is unticked."},
{id:"sa052",set:"2E",deck:"C",type:"Character",title:"Worn with Sorrow and Toil",cond:"Play on the table.",text:"When \"Worn with Sorrow and Toil\" is in play, if a Companion in the Fellowship is taken as a casualty you may also discard one of the Free Peoples player's Character Event cards from his hand (choosing it randomly) or from the table.\n\nYou must discard this card from the table immediately if the Fellowship is declared in an unconquered Free Peoples City or Stronghold.",ct:"Words of Power",cc:"Play if a Nazgûl is in the battle.",ctext:"Choose a Companion. That Companion's Leadership and special abilities are cancelled for this Combat round.",init:1,onTable:true,cpre:"nazInBattle",reminder:"When a Companion in the Fellowship is taken as a casualty, discard one Free Peoples Character Event card (random from the hand, or from the table). The app asks whether to discard it when the tracker shows the Fellowship revealed in a Free Peoples settlement."},
// ---- Warriors of Middle-earth event cards (added to the Character/Strategy decks)
{id:"sa01-F",set:"WoME",deck:"C",type:"Character",title:"Not on Anybody's Side",cond:"Play on the Table if any Free Peoples Faction is in play.",text:"No Faction Event card or Call to Battle card of the Ent or Eagle Factions can be played.\n\nThe Free Peoples player can force \"Not on Anybody's Side\" to be discarded by using a Will of the West Action Die result, or any Action die if Gandalf the White is in play.",ct:"Devilry of Orthanc",cc:"Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.",ctext:"Add 1 to all dice on your Combat roll.",init:3,onTable:true,pre:"fpFaction",cpre:"isengardStronghold",reminder:"The Free Peoples player can force its discard with a Will of the West die, or any die if Gandalf the White is in play — press Discard when that happens."},
{id:"sa04-F",set:"WoME",deck:"S",type:"Army",title:"Strongly Guarded",cond:"Play on the table.",text:"No Free Peoples Faction may move into a region containing a Stronghold controlled by the Shadow player or attack a Shadow Army in such a region, and their Call to Battle effects may not be used in such battles.\n\nThe Free Peoples player can force \"Strongly Guarded\" to be discarded by using a Will of the West Action Die result, or any Action die and one Elven Ring.",ct:"Deadly Strife",cc:null,ctext:"Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",init:3,onTable:true,reminder:"The Free Peoples player can force its discard with a Will of the West die, or any die plus an Elven Ring — press Discard when that happens."},
{id:"sa05-F",set:"WoME",deck:"S",type:"Muster",title:"Great Winged Creatures",cond:"Play if all Shadow Nations are \"At War.\"",text:"Recruit a Nazgûl in each Shadow Army containing at least one Nazgûl (excluding the Witch-king).",ct:"Relentless Assault",cc:null,ctext:"Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",init:3,pre:"allAtWar"},
// ---- Warriors of Middle-earth Faction Event cards
{id:"sa_Faction01",set:"WoME",deck:"F",type:"Muster",title:"A Great Fleet",cond:null,text:"Recruit one Corsairs figure in Umbar (or add it to the starting setup). Then, if the Corsairs are in play, move all Corsairs up to four regions.",faction:"Corsairs",effect:"recruitFaction"},
{id:"sa_Faction02",set:"WoME",deck:"F",type:"Muster",title:"A Great Fleet",cond:null,text:"Recruit one Corsairs figure in Umbar (or add it to the starting setup). Then, if the Corsairs are in play, move all Corsairs up to four regions.",faction:"Corsairs",effect:"recruitFaction"},
{id:"sa_Faction03",set:"WoME",deck:"F",type:"Character",title:"Black Sails",cond:"Play on the table if the Corsairs of Umbar are in play.",text:"You may use any Faction die result to either recruit one Corsairs figure in Umbar, or move all Corsairs up to four regions.\n\nThen, if the Fellowship is \"At Sea\" or revealed in a Gondor region, West Harondor, or Osgiliath, you may discard one Corsairs figure to inflict one point of Hunt Damage, following the rules for a successful Hunt.",faction:"Corsairs",onTable:true,pre:"corsairs",reminder:"Any Faction die result may recruit one Corsair in Umbar or move all Corsairs up to four regions (the Draw Faction Event page checks for a siege to sail to). If the Fellowship is at sea, or revealed in a Gondor region, West Harondor or Osgiliath, discard one Corsairs figure to inflict one point of Hunt damage."},
{id:"sa_Faction04",set:"WoME",deck:"F",type:"Army",title:"Ships of Great Draught",cond:null,text:"Transport Armies with Corsairs (each Corsairs figure may transport up to two Shadow units, and any number of Minions or Nazgûl, in its region): transport up to two Shadow Armies, up to four regions; or transport one Shadow Army up to two regions, and attack with that Army.",faction:"Corsairs",},
{id:"sa_Faction05",set:"WoME",deck:"F",type:"Army",title:"Ships of Great Draught",cond:null,text:"Transport Armies with Corsairs (each Corsairs figure may transport up to two Shadow units, and any number of Minions or Nazgûl, in its region): transport up to two Shadow Armies, up to four regions; or transport one Shadow Army up to two regions, and attack with that Army.",faction:"Corsairs",},
{id:"sa_Faction06",set:"WoME",deck:"F",type:"Muster",title:"Wild Hillmen",cond:null,text:"Recruit one Dunlending figure in each free Dunland Settlement (or add them to the starting setup).\n\nThen, if the Dunlendings are in play, move all Dunlendings up to two regions.",faction:"Dunlendings",effect:"recruitFaction"},
{id:"sa_Faction07",set:"WoME",deck:"F",type:"Muster",title:"Wild Hillmen",cond:null,text:"Recruit one Dunlending figure in each free Dunland Settlement (or add them to the starting setup).\n\nThen, if the Dunlendings are in play, move all Dunlendings up to two regions.",faction:"Dunlendings",effect:"recruitFaction"},
{id:"sa_Faction08",set:"WoME",deck:"F",type:"Army",title:"Death to the Forgoil",cond:null,text:"Attack a Free Peoples Army including Rohan and/or Gondor units with a Shadow Army in the same region with Dunlending figures. Dunlendings are considered as Isengard Regular units until the end of the battle.",faction:"Dunlendings",},
{id:"sa_Faction09",set:"WoME",deck:"F",type:"Army",title:"Death to the Forgoil",cond:null,text:"Attack a Free Peoples Army including Rohan and/or Gondor units with a Shadow Army in the same region with Dunlending figures. Dunlendings are considered as Isengard Regular units until the end of the battle.",faction:"Dunlendings",},
{id:"sa_Faction10",set:"WoME",deck:"F",type:"Character",title:"Armed by Saruman",cond:"Play on the table if Isengard is \"At War.\"",text:"When this card is in play, Dunlending figures in a region with the Fellowship are considered Shadow Army units for the purpose of the Hunt.\n\nDunlending figures in the same region with a Shadow Army add to its Combat Strength when one of their Call to Battle effects is used and can be taken as casualties against Ent attacks.\n\nThe Free Peoples player can force \"Armed by Saruman\" to be discarded by using a Will of the West Action die result.",faction:"Dunlendings",onTable:true,pre:"isengardAtWar",reminder:"The Free Peoples player can force its discard with a Will of the West die — press Discard when that happens."},
{id:"sa_Faction11",set:"WoME",deck:"F",type:"Character",title:"The Craft of Shelob",cond:null,text:"Move all Spiders up to two regions.\n\nIf the \"Shelob's Lair\" special Hunt tile has not entered play, it is now in play. Add the tile to the Hunt Pool when the Fellowship is on the Mordor Track.",faction:"Spiders",tile:true},
{id:"sa_Faction12",set:"WoME",deck:"F",type:"Character",title:"Evil Things",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Move all Spiders up to two regions. Then, you may discard one Spider figure in the region with the Fellowship to draw a Hunt tile.\n\nIf the tile shows an Eye, discard it without effect.\n\nOtherwise, follow the rules for a successful Hunt.",faction:"Spiders",tile:true,pre:"fsNotInFPSettlement"},
{id:"sa_Faction13",set:"WoME",deck:"F",type:"Character",title:"Children of Ungoliant",cond:"Play if the Fellowship is not in a region containing a Free Peoples Settlement.",text:"Move all Spiders up to two regions. Then, you may discard one Spider figure in the region with the Fellowship to inflict one point of Hunt Damage, following the rules for a successful Hunt. If the Fellowship is hidden, the Free Peoples player may choose to reveal it to prevent this damage.",faction:"Spiders",pre:"fsNotInFPSettlement"},
{id:"sa_Faction14",set:"WoME",deck:"F",type:"Army",title:"Huge and Horrible",cond:"Play on the table if Sauron is \"At War\".",text:"When this card is in play, Spider figures in a region with the Fellowship are considered Shadow Army units for the purpose of the Hunt.\n\nSpider figures in the same region with a Shadow Army add to its Combat Strength when one of their Call to Battle effects is used.\n\nThe Free Peoples player can force \"Huge and Horrible\" to be discarded by using a Will of the West Action die result.",faction:"Spiders",onTable:true,pre:"sauronAtWar",reminder:"The Free Peoples player can force its discard with a Will of the West die — press Discard when that happens."},
{id:"sa_Faction15",set:"WoME",deck:"F",type:"Muster",title:"Her Own Offspring",cond:null,text:"Recruit one Spider figure in Dol Guldur and one in Minas Morgul (or add them to the starting setup). Then, if the Spiders are in play, move all Spiders up to two regions.",faction:"Spiders",effect:"recruitFaction"},
{id:"sa_Faction16",set:"WoME",deck:"F",type:"Muster",title:"His Will and His Malice",cond:null,text:"Choose one Faction Event card in your discard pile and add it to your hand.",faction:null,effect:"hisWill"},
{id:"sa_Faction17",set:"WoME",deck:"F",type:"Muster",title:"His Will and His Malice",cond:null,text:"Choose one Faction Event card in your discard pile and add it to your hand.",faction:null,effect:"hisWill"},
{id:"sa_Faction18",set:"WoME",deck:"F",type:"Character",title:"Servants of Sauron",cond:null,text:"Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",faction:null,effect:"servants"},
{id:"sa_Faction19",set:"WoME",deck:"F",type:"Character",title:"Servants of Sauron",cond:null,text:"Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",faction:null,effect:"servants"},
{id:"sa_Faction20",set:"WoME",deck:"F",type:"Character",title:"Servants of Sauron",cond:null,text:"Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",faction:null,effect:"servants"},
// ---- Warriors of Middle-earth Call to Battle cards (not drawn; available when the faction is in play)
{id:"sa_battle01",set:"WoME",deck:"B",type:null,title:"Borne up on the Wind",cond:"Play if there are Corsairs in the same region as the Shadow Army, and the Shadow Army is not under siege.",text:"After casualties are applied, you may eliminate one of these Corsairs figures to transport up to two Shadow units from adjacent regions to the region with the Shadow Army.",init:7,faction:"Corsairs",cpre:"ctbNotBesieged"},
{id:"sa_battle02",set:"WoME",deck:"B",type:null,title:"The Last Stroke of Doom",cond:"Play if there are Corsairs in the same region as the Shadow Army, and the Shadow Army is attacking in a siege battle.",text:"At the end of the round, you may eliminate one of these Corsairs figures to extend the battle for an additional round (without reducing an Elite unit).",init:8,faction:"Corsairs",cpre:"ctbAttackingSiege"},
{id:"sa_battle03",set:"WoME",deck:"B",type:null,title:"Fierce Folk",cond:"Play if there are Dunlendings in the same region as the Shadow Army, and the Shadow Army is not under siege.",text:"Before you remove casualties, you may eliminate one or more of these Dunlending figures to cancel one hit for each figure you eliminated.\n\nIf “Armed By Saruman” is in play, Dunlendings add to the Combat Strength of the Shadow Army in this round.",init:6,faction:"Dunlendings",cpre:"ctbNotBesieged"},
{id:"sa_battle04",set:"WoME",deck:"B",type:null,title:"Old Hatred",cond:"Play if there are Dunlendings in the same region as the Shadow Army, and the Shadow Army is not under siege.",text:"Before the Combat roll, roll one die for each of these Dunlending figures. Eliminate one Dunlending for each result of 1, and score one hit for each result of 6.\n\nIf “Armed By Saruman” is in play, Dunlendings add to the Combat Strength of the Shadow Army in this round.",init:2,faction:"Dunlendings",cpre:"ctbNotBesieged"},
{id:"sa_battle05",set:"WoME",deck:"B",type:null,title:"Webs of Shadow",cond:"Play if there are Spiders in the same region as the Shadow Army.",text:"If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-combat attack from a Combat card or Faction Call to Battle card), you may eliminate one of these Spider figures to score one additional hit.\n\nIf “Huge and Horrible” is in play, Spiders add to the Combat Strength of the Shadow Army in this round.",init:7,faction:"Spiders",cpre:"ctb"},
{id:"sa_battle06",set:"WoME",deck:"B",type:null,title:"Hideous Speed",cond:"Play if there are Spiders in the same region as the Shadow Army.",text:"Before the Combat roll, roll one die. On a result of 1 or 2, eliminate one of these Spider figures. On a result of 5 or 6, eliminate a Free Peoples Leader or a Level 1 Companion in the battle.\n\nIf “Huge and Horrible” is in play, Spiders add to the Combat Strength of the Shadow Army in this round.",init:2,faction:"Spiders",cpre:"ctb"}
];


// Reference text from "Queller Bot for War of the Ring" v3.3 (Quitch, CC BY-NC 4.0)
