// The Warriors of Middle-earth cards: three event cards added to the Character/Strategy decks, the Faction Event deck and
// the Call to Battle cards. Same fields and flags as base.js.
export const WOME_CARDS = [
  {
    id: "sa01-F",
    set: "WoME",
    deck: "C",
    type: "Character",
    title: "Not on Anybody's Side",
    cond: "Play on the Table if any Free Peoples Faction is in play.",
    text: 'No Faction Event card or Call to Battle card of the Ent or Eagle Factions can be played.\n\nThe Free Peoples player can force "Not on Anybody\'s Side" to be discarded by using a Will of the West Action Die result, or any Action die if Gandalf the White is in play.',
    combatTitle: "Devilry of Orthanc",
    combatCond:
      "Play if an Isengard Army unit is in the battle and the defending Army is in a Stronghold.",
    combatText: "Add 1 to all dice on your Combat roll.",
    init: 3,
    onTable: true,
    pre: "fpFaction",
    cpre: "isengardStronghold",
    reminder:
      "The Free Peoples player can force its discard with a Will of the West die, or any die if Gandalf the White is in play — press Discard when that happens.",
  },
  {
    id: "sa04-F",
    set: "WoME",
    deck: "S",
    type: "Army",
    title: "Strongly Guarded",
    cond: "Play on the table.",
    text: 'No Free Peoples Faction may move into a region containing a Stronghold controlled by the Shadow player or attack a Shadow Army in such a region, and their Call to Battle effects may not be used in such battles.\n\nThe Free Peoples player can force "Strongly Guarded" to be discarded by using a Will of the West Action Die result, or any Action die and one Elven Ring.',
    combatTitle: "Deadly Strife",
    combatCond: null,
    combatText:
      "Both Armies add 2 to all dice on their Combat roll and Leader re-roll.",
    init: 3,
    onTable: true,
    reminder:
      "The Free Peoples player can force its discard with a Will of the West die, or any die plus an Elven Ring — press Discard when that happens.",
  },
  {
    id: "sa05-F",
    set: "WoME",
    deck: "S",
    type: "Muster",
    title: "Great Winged Creatures",
    cond: 'Play if all Shadow Nations are "At War."',
    text: "Recruit a Nazgûl in each Shadow Army containing at least one Nazgûl (excluding the Witch-king).",
    combatTitle: "Relentless Assault",
    combatCond: null,
    combatText:
      "Before the Combat roll, you may inflict and apply up to two hits against your units. Add 1 to all dice on your Combat roll for each hit you inflicted.",
    init: 3,
    pre: "allAtWar",
  },
  // ---- Warriors of Middle-earth Faction Event cards
  {
    id: "sa_Faction01",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "A Great Fleet",
    cond: null,
    text: "Recruit one Corsairs figure in Umbar (or add it to the starting setup). Then, if the Corsairs are in play, move all Corsairs up to four regions.",
    faction: "Corsairs",
    effect: "recruitFaction",
  },
  {
    id: "sa_Faction02",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "A Great Fleet",
    cond: null,
    text: "Recruit one Corsairs figure in Umbar (or add it to the starting setup). Then, if the Corsairs are in play, move all Corsairs up to four regions.",
    faction: "Corsairs",
    effect: "recruitFaction",
  },
  {
    id: "sa_Faction03",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Black Sails",
    cond: "Play on the table if the Corsairs of Umbar are in play.",
    text: 'You may use any Faction die result to either recruit one Corsairs figure in Umbar, or move all Corsairs up to four regions.\n\nThen, if the Fellowship is "At Sea" or revealed in a Gondor region, West Harondor, or Osgiliath, you may discard one Corsairs figure to inflict one point of Hunt Damage, following the rules for a successful Hunt.',
    faction: "Corsairs",
    onTable: true,
    pre: "corsairs",
    reminder:
      "Any Faction die result may recruit one Corsair in Umbar or move all Corsairs up to four regions (the Draw Faction Event page checks for a siege to sail to). If the Fellowship is at sea, or revealed in a Gondor region, West Harondor or Osgiliath, discard one Corsairs figure to inflict one point of Hunt damage.",
  },
  {
    id: "sa_Faction04",
    set: "WoME",
    deck: "F",
    type: "Army",
    title: "Ships of Great Draught",
    cond: null,
    text: "Transport Armies with Corsairs (each Corsairs figure may transport up to two Shadow units, and any number of Minions or Nazgûl, in its region): transport up to two Shadow Armies, up to four regions; or transport one Shadow Army up to two regions, and attack with that Army.",
    faction: "Corsairs",
  },
  {
    id: "sa_Faction05",
    set: "WoME",
    deck: "F",
    type: "Army",
    title: "Ships of Great Draught",
    cond: null,
    text: "Transport Armies with Corsairs (each Corsairs figure may transport up to two Shadow units, and any number of Minions or Nazgûl, in its region): transport up to two Shadow Armies, up to four regions; or transport one Shadow Army up to two regions, and attack with that Army.",
    faction: "Corsairs",
  },
  {
    id: "sa_Faction06",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "Wild Hillmen",
    cond: null,
    text: "Recruit one Dunlending figure in each free Dunland Settlement (or add them to the starting setup).\n\nThen, if the Dunlendings are in play, move all Dunlendings up to two regions.",
    faction: "Dunlendings",
    effect: "recruitFaction",
  },
  {
    id: "sa_Faction07",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "Wild Hillmen",
    cond: null,
    text: "Recruit one Dunlending figure in each free Dunland Settlement (or add them to the starting setup).\n\nThen, if the Dunlendings are in play, move all Dunlendings up to two regions.",
    faction: "Dunlendings",
    effect: "recruitFaction",
  },
  {
    id: "sa_Faction08",
    set: "WoME",
    deck: "F",
    type: "Army",
    title: "Death to the Forgoil",
    cond: null,
    text: "Attack a Free Peoples Army including Rohan and/or Gondor units with a Shadow Army in the same region with Dunlending figures. Dunlendings are considered as Isengard Regular units until the end of the battle.",
    faction: "Dunlendings",
  },
  {
    id: "sa_Faction09",
    set: "WoME",
    deck: "F",
    type: "Army",
    title: "Death to the Forgoil",
    cond: null,
    text: "Attack a Free Peoples Army including Rohan and/or Gondor units with a Shadow Army in the same region with Dunlending figures. Dunlendings are considered as Isengard Regular units until the end of the battle.",
    faction: "Dunlendings",
  },
  {
    id: "sa_Faction10",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Armed by Saruman",
    cond: 'Play on the table if Isengard is "At War."',
    text: 'When this card is in play, Dunlending figures in a region with the Fellowship are considered Shadow Army units for the purpose of the Hunt.\n\nDunlending figures in the same region with a Shadow Army add to its Combat Strength when one of their Call to Battle effects is used and can be taken as casualties against Ent attacks.\n\nThe Free Peoples player can force "Armed by Saruman" to be discarded by using a Will of the West Action die result.',
    faction: "Dunlendings",
    onTable: true,
    pre: "isengardAtWar",
    reminder:
      "The Free Peoples player can force its discard with a Will of the West die — press Discard when that happens.",
  },
  {
    id: "sa_Faction11",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "The Craft of Shelob",
    cond: null,
    text: 'Move all Spiders up to two regions.\n\nIf the "Shelob\'s Lair" special Hunt tile has not entered play, it is now in play. Add the tile to the Hunt Pool when the Fellowship is on the Mordor Track.',
    faction: "Spiders",
    tile: true,
  },
  {
    id: "sa_Faction12",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Evil Things",
    cond: "Play if the Fellowship is not in a region containing a Free Peoples Settlement.",
    text: "Move all Spiders up to two regions. Then, you may discard one Spider figure in the region with the Fellowship to draw a Hunt tile.\n\nIf the tile shows an Eye, discard it without effect.\n\nOtherwise, follow the rules for a successful Hunt.",
    faction: "Spiders",
    tile: true,
    pre: "fsNotInFPSettlement",
  },
  {
    id: "sa_Faction13",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Children of Ungoliant",
    cond: "Play if the Fellowship is not in a region containing a Free Peoples Settlement.",
    text: "Move all Spiders up to two regions. Then, you may discard one Spider figure in the region with the Fellowship to inflict one point of Hunt Damage, following the rules for a successful Hunt. If the Fellowship is hidden, the Free Peoples player may choose to reveal it to prevent this damage.",
    faction: "Spiders",
    pre: "fsNotInFPSettlement",
  },
  {
    id: "sa_Faction14",
    set: "WoME",
    deck: "F",
    type: "Army",
    title: "Huge and Horrible",
    cond: 'Play on the table if Sauron is "At War".',
    text: 'When this card is in play, Spider figures in a region with the Fellowship are considered Shadow Army units for the purpose of the Hunt.\n\nSpider figures in the same region with a Shadow Army add to its Combat Strength when one of their Call to Battle effects is used.\n\nThe Free Peoples player can force "Huge and Horrible" to be discarded by using a Will of the West Action die result.',
    faction: "Spiders",
    onTable: true,
    pre: "sauronAtWar",
    reminder:
      "The Free Peoples player can force its discard with a Will of the West die — press Discard when that happens.",
  },
  {
    id: "sa_Faction15",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "Her Own Offspring",
    cond: null,
    text: "Recruit one Spider figure in Dol Guldur and one in Minas Morgul (or add them to the starting setup). Then, if the Spiders are in play, move all Spiders up to two regions.",
    faction: "Spiders",
    effect: "recruitFaction",
  },
  {
    id: "sa_Faction16",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "His Will and His Malice",
    cond: null,
    text: "Choose one Faction Event card in your discard pile and add it to your hand.",
    faction: null,
    effect: "hisWill",
  },
  {
    id: "sa_Faction17",
    set: "WoME",
    deck: "F",
    type: "Muster",
    title: "His Will and His Malice",
    cond: null,
    text: "Choose one Faction Event card in your discard pile and add it to your hand.",
    faction: null,
    effect: "hisWill",
  },
  {
    id: "sa_Faction18",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Servants of Sauron",
    cond: null,
    text: "Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",
    faction: null,
    effect: "servants",
  },
  {
    id: "sa_Faction19",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Servants of Sauron",
    cond: null,
    text: "Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",
    faction: null,
    effect: "servants",
  },
  {
    id: "sa_Faction20",
    set: "WoME",
    deck: "F",
    type: "Character",
    title: "Servants of Sauron",
    cond: null,
    text: "Draw three cards from the Faction Event deck. Add one card to your hand, then reshuffle the remaining two cards into the deck, together with the Faction Event cards in your discard pile (including this one).",
    faction: null,
    effect: "servants",
  },
  // ---- Warriors of Middle-earth Call to Battle cards (not drawn; available when the faction is in play)
  {
    id: "sa_battle01",
    set: "WoME",
    deck: "B",
    type: null,
    title: "Borne up on the Wind",
    cond: "Play if there are Corsairs in the same region as the Shadow Army, and the Shadow Army is not under siege.",
    text: "After casualties are applied, you may eliminate one of these Corsairs figures to transport up to two Shadow units from adjacent regions to the region with the Shadow Army.",
    init: 7,
    faction: "Corsairs",
    cpre: "ctbNotBesieged",
  },
  {
    id: "sa_battle02",
    set: "WoME",
    deck: "B",
    type: null,
    title: "The Last Stroke of Doom",
    cond: "Play if there are Corsairs in the same region as the Shadow Army, and the Shadow Army is attacking in a siege battle.",
    text: "At the end of the round, you may eliminate one of these Corsairs figures to extend the battle for an additional round (without reducing an Elite unit).",
    init: 8,
    faction: "Corsairs",
    cpre: "ctbAttackingSiege",
  },
  {
    id: "sa_battle03",
    set: "WoME",
    deck: "B",
    type: null,
    title: "Fierce Folk",
    cond: "Play if there are Dunlendings in the same region as the Shadow Army, and the Shadow Army is not under siege.",
    text: "Before you remove casualties, you may eliminate one or more of these Dunlending figures to cancel one hit for each figure you eliminated.\n\nIf “Armed By Saruman” is in play, Dunlendings add to the Combat Strength of the Shadow Army in this round.",
    init: 6,
    faction: "Dunlendings",
    cpre: "ctbNotBesieged",
  },
  {
    id: "sa_battle04",
    set: "WoME",
    deck: "B",
    type: null,
    title: "Old Hatred",
    cond: "Play if there are Dunlendings in the same region as the Shadow Army, and the Shadow Army is not under siege.",
    text: "Before the Combat roll, roll one die for each of these Dunlending figures. Eliminate one Dunlending for each result of 1, and score one hit for each result of 6.\n\nIf “Armed By Saruman” is in play, Dunlendings add to the Combat Strength of the Shadow Army in this round.",
    init: 2,
    faction: "Dunlendings",
    cpre: "ctbNotBesieged",
  },
  {
    id: "sa_battle05",
    set: "WoME",
    deck: "B",
    type: null,
    title: "Webs of Shadow",
    cond: "Play if there are Spiders in the same region as the Shadow Army.",
    text: "If, after the Leader re-roll, you scored more total hits than your opponent (including hits from any Free Peoples pre-combat attack from a Combat card or Faction Call to Battle card), you may eliminate one of these Spider figures to score one additional hit.\n\nIf “Huge and Horrible” is in play, Spiders add to the Combat Strength of the Shadow Army in this round.",
    init: 7,
    faction: "Spiders",
    cpre: "ctb",
  },
  {
    id: "sa_battle06",
    set: "WoME",
    deck: "B",
    type: null,
    title: "Hideous Speed",
    cond: "Play if there are Spiders in the same region as the Shadow Army.",
    text: "Before the Combat roll, roll one die. On a result of 1 or 2, eliminate one of these Spider figures. On a result of 5 or 6, eliminate a Free Peoples Leader or a Level 1 Companion in the battle.\n\nIf “Huge and Horrible” is in play, Spiders add to the Combat Strength of the Shadow Army in this round.",
    init: 2,
    faction: "Spiders",
    cpre: "ctb",
  },
];
